apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: catalogue
  namespace: catalogue-microservice
  labels:
    project: Robot-Shop
    technology: HAProxy
    environment: dev 
  annotations:
    haproxy.org/path-rewrite: /catalogue/(.*) /\1

spec:
  ingressClassName: haproxy
  rules:
  - http:
      paths:
      - path: /catalogue
        pathType: Prefix
        backend:
          service:
            name: catalogue
            port:
              number: 8226