apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: shipping
  namespace: shipping-microservice
  labels:
    project: Robot-Shop
    technology: HAProxy
    environment: dev 
  annotations:
    haproxy.org/path-rewrite: /shipping/(.*) /\1

spec:
  ingressClassName: haproxy
  rules:
  - http:
      paths:
      - path: /shipping
        pathType: Prefix
        backend:
          service:
            name: shipping
            port:
              number: 8526