apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: user
  namespace: user-microservice
  labels:
    project: Robot-Shop
    technology: HAProxy
    environment: dev 
  annotations:
    haproxy.org/path-rewrite: /user/(.*) /\1

spec:
  ingressClassName: haproxy
  rules:
  - http:
      paths:
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: user
            port:
              number: 8126